# Generated by Django 5.2.7 on 2025-10-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(help_text='招聘职位', max_length=200)),
                ('description', models.TextField(help_text='职位描述和要求')),
                ('department', models.CharField(max_length=100)),
                ('number_of_positions', models.PositiveIntegerField(default=1, help_text='招聘人数')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted to HR'), ('in_progress', 'Recruiting'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('hr_notes', models.TextField(blank=True, help_text='HR 备注')),
                ('candidates_interviewed', models.PositiveIntegerField(default=0)),
                ('positions_filled', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, help_text='开始招聘时间', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成招聘时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
