# Generated by Django 5.2.7 on 2025-10-27 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='hr_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_recruitments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
