from django.core.management.base import BaseCommand
from django.utils import timezone
from datetime import timedelta
from apps.users.models import User
from apps.event_requests.models import EventRequest


class Command(BaseCommand):
    help = '创建事件请求的模拟数据'

    def handle(self, *args, **kwargs):
        # 获取现有用户
        try:
            cs_user = User.objects.get(username='Sarah')
            scs_user = User.objects.get(username='Janet')
            fm_user = User.objects.get(username='Alice')
            admin_user = User.objects.get(username='Mike')
        except User.DoesNotExist:
            self.stdout.write(
                self.style.ERROR('错误: 请先运行 loaduser 命令创建用户')
            )
            return

        now = timezone.now()

        event_requests_data = [
            # ========== SUBMITTED 状态 (2条) ==========
            {
                'title': 'Tech Conference 2024 - ABC Corp',
                'description': 'Event request for ABC Corp',
                'record_number': 'ER-2024-001',
                'client_name': 'ABC Corp',
                'event_type': 'Conference',
                'expected_number': 150,
                'expected_budget': 75000.00,
                'from_date': now.date() + timedelta(days=30),
                'to_date': now.date() + timedelta(days=32),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': False,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'submitted',
                'created_at': now - timedelta(hours=2),
                'updated_at': now - timedelta(hours=2),
            },
            {
                'title': 'Wedding Reception - Smith Family',
                'description': 'Event request for Smith Family',
                'record_number': 'ER-2024-002',
                'client_name': 'Smith Family',
                'event_type': 'Wedding',
                'expected_number': 200,
                'expected_budget': 120000.00,
                'from_date': now.date() + timedelta(days=60),
                'to_date': now.date() + timedelta(days=60),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': True,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'submitted',
                'created_at': now - timedelta(hours=5),
                'updated_at': now - timedelta(hours=5),
            },
            # ========== SCS_REVIEWED 状态 (2条) ==========
            {
                'title': 'Product Launch - XYZ Tech',
                'description': 'Event request for XYZ Tech',
                'record_number': 'ER-2024-003',
                'client_name': 'XYZ Tech',
                'event_type': 'Product Launch',
                'expected_number': 300,
                'expected_budget': 150000.00,
                'from_date': now.date() + timedelta(days=45),
                'to_date': now.date() + timedelta(days=46),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': True,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'scs_reviewed',
                'created_at': now - timedelta(days=2),
                'updated_at': now - timedelta(hours=6),
                'scs_handler': scs_user,
                'scs_comment': 'Event details look comprehensive. Client is a valued customer with good payment history. Ready for financial review.',
                'scs_handled_at': now - timedelta(hours=6),
            },
            {
                'title': 'Corporate Training - Global Enterprises',
                'description': 'Event request for Global Enterprises',
                'record_number': 'ER-2024-004',
                'client_name': 'Global Enterprises',
                'event_type': 'Training Workshop',
                'expected_number': 80,
                'expected_budget': 45000.00,
                'from_date': now.date() + timedelta(days=25),
                'to_date': now.date() + timedelta(days=27),
                'has_decorations': False,
                'has_meals': True,
                'has_parties': False,
                'has_drinks': True,
                'has_filming': False,
                'created_by': cs_user,
                'status': 'scs_reviewed',
                'created_at': now - timedelta(days=1, hours=12),
                'updated_at': now - timedelta(hours=10),
                'scs_handler': scs_user,
                'scs_comment': 'Training event for repeat client. Budget is within normal range. Approved for FM review.',
                'scs_handled_at': now - timedelta(hours=10),
            },
            # ========== FM_REVIEWED 状态 (2条) ==========
            {
                'title': 'Charity Gala - Hope Foundation',
                'description': 'Event request for Hope Foundation',
                'record_number': 'ER-2024-005',
                'client_name': 'Hope Foundation',
                'event_type': 'Charity Gala',
                'expected_number': 250,
                'expected_budget': 180000.00,
                'from_date': now.date() + timedelta(days=50),
                'to_date': now.date() + timedelta(days=50),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': True,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'fm_reviewed',
                'created_at': now - timedelta(days=3),
                'updated_at': now - timedelta(hours=4),
                'scs_handler': scs_user,
                'scs_comment': 'High-profile charity event. Excellent opportunity for company PR. Recommend approval.',
                'scs_handled_at': now - timedelta(days=2, hours=18),
                'fm_handler': fm_user,
                'fm_feedback': 'Budget reviewed and approved. Expected ROI is positive. Payment terms: 50% deposit, 50% on completion.',
                'fm_handled_at': now - timedelta(hours=4),
            },
            {
                'title': 'Annual Meeting - InnovateCo',
                'description': 'Event request for InnovateCo',
                'record_number': 'ER-2024-006',
                'client_name': 'InnovateCo',
                'event_type': 'Annual Meeting',
                'expected_number': 120,
                'expected_budget': 65000.00,
                'from_date': now.date() + timedelta(days=35),
                'to_date': now.date() + timedelta(days=35),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': False,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'fm_reviewed',
                'created_at': now - timedelta(days=2, hours=8),
                'updated_at': now - timedelta(hours=2),
                'scs_handler': scs_user,
                'scs_comment': 'Regular annual meeting for existing client. Budget is in line with previous years.',
                'scs_handled_at': now - timedelta(days=1, hours=20),
                'fm_handler': fm_user,
                'fm_feedback': 'Budget approved. Client has excellent payment record. No financial concerns.',
                'fm_handled_at': now - timedelta(hours=2),
            },
            # ========== APPROVED 状态 (2条) ==========
            {
                'title': 'Summer Festival - City Council',
                'description': 'Event request for City Council',
                'record_number': 'ER-2024-007',
                'client_name': 'City Council',
                'event_type': 'Festival',
                'expected_number': 500,
                'expected_budget': 250000.00,
                'from_date': now.date() + timedelta(days=90),
                'to_date': now.date() + timedelta(days=92),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': True,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'approved',
                'created_at': now - timedelta(days=5),
                'updated_at': now - timedelta(hours=1),
                'scs_handler': scs_user,
                'scs_comment': 'Major city event with high visibility. Strategic importance for company portfolio.',
                'scs_handled_at': now - timedelta(days=4, hours=12),
                'fm_handler': fm_user,
                'fm_feedback': 'Large budget approved with staged payments. Government client - secure payment. Profit margin is healthy.',
                'fm_handled_at': now - timedelta(days=3, hours=8),
                'admin_handler': admin_user,
                'admin_decision': 'APPROVED. High-profile event aligns with company growth strategy. Allocate senior team members.',
                'admin_handled_at': now - timedelta(hours=1),
            },
            {
                'title': 'Industry Conference - TechVentures',
                'description': 'Event request for TechVentures',
                'record_number': 'ER-2024-008',
                'client_name': 'TechVentures',
                'event_type': 'Conference',
                'expected_number': 180,
                'expected_budget': 95000.00,
                'from_date': now.date() + timedelta(days=55),
                'to_date': now.date() + timedelta(days=57),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': True,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'approved',
                'created_at': now - timedelta(days=4, hours=6),
                'updated_at': now - timedelta(minutes=45),
                'scs_handler': scs_user,
                'scs_comment': 'Tech industry conference. New client with good references. Opportunity to expand into tech sector.',
                'scs_handled_at': now - timedelta(days=3, hours=14),
                'fm_handler': fm_user,
                'fm_feedback': 'Budget is reasonable. New client - require 60% deposit. Financial projections are sound.',
                'fm_handled_at': now - timedelta(days=2, hours=6),
                'admin_handler': admin_user,
                'admin_decision': 'APPROVED. Good opportunity to enter tech sector. Assign experienced project manager.',
                'admin_handled_at': now - timedelta(minutes=45),
            },
            # ========== REJECTED 状态 (2条) ==========
            {
                'title': 'Private Party - Johnson Estate',
                'description': 'Event request for Johnson Estate',
                'record_number': 'ER-2024-009',
                'client_name': 'Johnson Estate',
                'event_type': 'Private Party',
                'expected_number': 50,
                'expected_budget': 85000.00,
                'from_date': now.date() + timedelta(days=15),
                'to_date': now.date() + timedelta(days=15),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': True,
                'has_drinks': True,
                'has_filming': False,
                'created_by': cs_user,
                'status': 'rejected',
                'created_at': now - timedelta(days=6),
                'updated_at': now - timedelta(days=4),
                'scs_handler': scs_user,
                'scs_comment': 'Small event with very high budget per person. Client is new with no references. Timeline is very tight.',
                'scs_handled_at': now - timedelta(days=5, hours=16),
                'fm_handler': fm_user,
                'fm_feedback': 'Budget seems inflated. No payment history. High financial risk. Recommend rejection unless 100% prepayment.',
                'fm_handled_at': now - timedelta(days=5, hours=2),
                'admin_handler': admin_user,
                'admin_decision': 'REJECTED. Timeline too short for preparation. Financial risk too high for unknown client.',
                'admin_handled_at': now - timedelta(days=4),
            },
            {
                'title': 'Exhibition - StartupHub',
                'description': 'Event request for StartupHub',
                'record_number': 'ER-2024-010',
                'client_name': 'StartupHub',
                'event_type': 'Exhibition',
                'expected_number': 400,
                'expected_budget': 320000.00,
                'from_date': now.date() + timedelta(days=20),
                'to_date': now.date() + timedelta(days=23),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': True,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'rejected',
                'created_at': now - timedelta(days=7),
                'updated_at': now - timedelta(days=5, hours=8),
                'scs_handler': scs_user,
                'scs_comment': 'Large scale event with ambitious requirements. Startup client with limited track record.',
                'scs_handled_at': now - timedelta(days=6, hours=14),
                'fm_handler': fm_user,
                'fm_feedback': 'Budget is extremely high with uncertain ROI. Client financial stability is questionable.',
                'fm_handled_at': now - timedelta(days=6, hours=2),
                'admin_handler': admin_user,
                'admin_decision': 'REJECTED. Scale exceeds current capacity. Risk outweighs potential benefit.',
                'admin_handled_at': now - timedelta(days=5, hours=8),
            },
            # ========== OPEN 状态 (2条) ==========
            {
                'title': 'Awards Ceremony - MediaGroup',
                'description': 'Event request for MediaGroup',
                'record_number': 'ER-2024-011',
                'client_name': 'MediaGroup',
                'event_type': 'Awards Ceremony',
                'expected_number': 300,
                'expected_budget': 200000.00,
                'from_date': now.date() + timedelta(days=70),
                'to_date': now.date() + timedelta(days=70),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': True,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'open',
                'created_at': now - timedelta(days=10),
                'updated_at': now - timedelta(days=2),
                'scs_handler': scs_user,
                'scs_comment': 'Prestigious awards ceremony. Media client with excellent reputation. High visibility event.',
                'scs_handled_at': now - timedelta(days=9, hours=10),
                'fm_handler': fm_user,
                'fm_feedback': 'Budget approved. Client has strong financials. Expected profit margin 25%. Payment terms: 40% deposit, 40% mid-project, 20% completion.',
                'fm_handled_at': now - timedelta(days=8, hours=14),
                'admin_handler': admin_user,
                'admin_decision': 'APPROVED. Excellent showcase opportunity. Assign top-tier team. Ensure media coverage for company PR.',
                'admin_handled_at': now - timedelta(days=7, hours=20),
                'description_of_decorations': 'Red carpet entrance with gold and black theme. Crystal chandeliers, elegant draping, floral centerpieces.',
                'description_of_meals': 'Five-course gourmet dinner: Smoked salmon canapés, French onion soup, filet mignon or sea bass, chocolate fondant.',
                'description_of_music': 'Live jazz quartet during cocktail hour. DJ for after-ceremony celebration. Professional sound system.',
                'description_of_poster': 'Large format posters at entrance featuring award categories and nominees. Digital displays throughout venue.',
                'description_of_filming': 'Three professional cameras for live streaming. Drone footage. Photo booth. Professional photographer for red carpet.',
                'description_of_drinks': 'Premium open bar: champagne, wine selection, craft cocktails, mocktails. Signature cocktail for the event.',
                'other_needs': 'VIP green room. Security. Valet parking. Event coordinator on-site. Award trophies and certificates.',
            },
            {
                'title': 'Trade Show - International Commerce Association',
                'description': 'Event request for International Commerce Association',
                'record_number': 'ER-2024-012',
                'client_name': 'International Commerce Association',
                'event_type': 'Trade Show',
                'expected_number': 600,
                'expected_budget': 380000.00,
                'from_date': now.date() + timedelta(days=100),
                'to_date': now.date() + timedelta(days=103),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': False,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'open',
                'created_at': now - timedelta(days=12),
                'updated_at': now - timedelta(days=3),
                'scs_handler': scs_user,
                'scs_comment': 'Major international trade show. Repeat client with 5-year relationship. Strategic importance.',
                'scs_handled_at': now - timedelta(days=11, hours=8),
                'fm_handler': fm_user,
                'fm_feedback': 'Large budget approved. Client payment history excellent. Projected margin 22%. Milestone-based payment schedule.',
                'fm_handled_at': now - timedelta(days=10, hours=12),
                'admin_handler': admin_user,
                'admin_decision': 'APPROVED. Flagship event for international portfolio. Full team allocation.',
                'admin_handled_at': now - timedelta(days=9, hours=16),
                'description_of_decorations': 'Exhibition hall with 100 vendor booths. Modern design. Registration area with digital check-in kiosks.',
                'description_of_meals': 'Daily lunch buffets: International cuisine, vegetarian and vegan options. Coffee and refreshment stations.',
                'description_of_music': 'Background ambient music. Professional PA system. Audio support for 5 simultaneous breakout sessions.',
                'description_of_poster': 'Large format directional signage. Booth numbers and floor maps. Sponsor recognition boards.',
                'description_of_filming': 'Live streaming of keynote presentations. Video recording. Professional photography. Time-lapse of event.',
                'description_of_drinks': 'Coffee stations with barista service. Hydration stations. VIP hospitality suite with premium beverages.',
                'other_needs': 'WiFi for 1000+ devices. Translation services (5 languages). Registration. AV equipment. 24-hour security. First aid.',
            },
            # ========== IN_PROGRESS 状态 (2条) ==========
            {
                'title': 'Corporate Retreat - FinanceCorp',
                'description': 'Event request for FinanceCorp',
                'record_number': 'ER-2024-013',
                'client_name': 'FinanceCorp',
                'event_type': 'Corporate Retreat',
                'expected_number': 100,
                'expected_budget': 125000.00,
                'from_date': now.date() - timedelta(days=1),
                'to_date': now.date() + timedelta(days=2),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': False,
                'has_drinks': True,
                'has_filming': False,
                'created_by': cs_user,
                'status': 'in_progress',
                'created_at': now - timedelta(days=45),
                'updated_at': now - timedelta(days=1),
                'scs_handler': scs_user,
                'scs_comment': 'Annual corporate retreat. Long-standing client relationship. Executive level event.',
                'scs_handled_at': now - timedelta(days=44),
                'fm_handler': fm_user,
                'fm_feedback': 'Budget approved. Standard corporate rates. Payment received in full upfront.',
                'fm_handled_at': now - timedelta(days=43),
                'admin_handler': admin_user,
                'admin_decision': 'APPROVED. Priority client. Ensure VIP treatment and flawless execution.',
                'admin_handled_at': now - timedelta(days=42),
                'description_of_decorations': 'Professional corporate theme. Company colors incorporated. Welcome banners.',
                'description_of_meals': 'Breakfast buffets, working lunches, formal dinners. Dietary restrictions accommodated.',
                'description_of_music': 'Soft background music during meals. AV system for presentations.',
                'description_of_poster': 'Welcome signage. Agenda boards. Company branding elements.',
                'description_of_drinks': 'Premium beverage service. Wine with dinners. Full bar for evening networking.',
                'other_needs': 'Team building activities coordinator. Breakout rooms. Printed materials. Transportation coordination.',
            },
            {
                'title': 'Graduation Ceremony - University College',
                'description': 'Event request for University College',
                'record_number': 'ER-2024-014',
                'client_name': 'University College',
                'event_type': 'Graduation Ceremony',
                'expected_number': 800,
                'expected_budget': 180000.00,
                'from_date': now.date(),
                'to_date': now.date(),
                'has_decorations': True,
                'has_meals': False,
                'has_parties': False,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'in_progress',
                'created_at': now - timedelta(days=60),
                'updated_at': now,
                'scs_handler': scs_user,
                'scs_comment': 'Annual graduation ceremony. Important academic milestone. High profile event.',
                'scs_handled_at': now - timedelta(days=59),
                'fm_handler': fm_user,
                'fm_feedback': 'Educational institution pricing applied. Budget approved. Payment schedule aligned with academic calendar.',
                'fm_handled_at': now - timedelta(days=58),
                'admin_handler': admin_user,
                'admin_decision': 'APPROVED. Community service aspect. Good PR opportunity. Assign experienced ceremony team.',
                'admin_handled_at': now - timedelta(days=57),
                'description_of_decorations': 'Stage setup with university branding. Floral arrangements. Ceremonial decorations in school colors.',
                'description_of_music': 'Processional and recessional music. Sound system for speeches. Live musicians for ceremony.',
                'description_of_poster': 'Directional signage for guests. Photo opportunity backdrop. Congratulatory banners.',
                'description_of_filming': 'Professional video recording. Live streaming for remote attendees. Photography package for graduates.',
                'description_of_drinks': 'Reception area with refreshments. Coffee and tea service. Light refreshments for guests.',
                'other_needs': 'Stage and podium setup. Graduate procession coordination. Diploma distribution. Parking. Seating for 1000+ guests.',
            },
            # ========== CLOSED 状态 (2条) ==========
            {
                'title': 'New Year Gala - Luxury Hotels Group',
                'description': 'Event request for Luxury Hotels Group',
                'record_number': 'ER-2024-015',
                'client_name': 'Luxury Hotels Group',
                'event_type': 'Gala',
                'expected_number': 400,
                'expected_budget': 280000.00,
                'from_date': now.date() - timedelta(days=30),
                'to_date': now.date() - timedelta(days=30),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': True,
                'has_drinks': True,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'closed',
                'created_at': now - timedelta(days=90),
                'updated_at': now - timedelta(days=25),
                'scs_handler': scs_user,
                'scs_comment': 'Premium New Year celebration. VIP client. Luxury tier service required.',
                'scs_handled_at': now - timedelta(days=89),
                'fm_handler': fm_user,
                'fm_feedback': 'High-value event. Premium pricing approved. All payments completed successfully.',
                'fm_handled_at': now - timedelta(days=88),
                'admin_handler': admin_user,
                'admin_decision': 'APPROVED. Showcase event. Deploy best resources. Opportunity for portfolio photos.',
                'admin_handled_at': now - timedelta(days=87),
                'description_of_decorations': 'Luxury New Year theme. Gold and silver decor. Balloon drop at midnight. Ice sculptures.',
                'description_of_meals': 'Gourmet seven-course dinner. Michelin-star chef. Caviar station. Premium ingredients throughout.',
                'description_of_music': 'Live orchestra. International DJ. Entertainment acts. Countdown coordination.',
                'description_of_poster': 'Elegant event branding. Welcome displays. Sponsor recognition.',
                'description_of_filming': 'Multi-camera setup. Highlight reel production. Social media content. Guest photography service.',
                'description_of_drinks': 'Premium champagne. Top-shelf spirits. Specialty cocktails. Wine pairing with dinner.',
                'other_needs': 'Valet service. Coat check. Security team. Event hostesses. Fireworks display. Photo booth. Party favors.',
            },
            {
                'title': 'Science Fair - Youth Education Foundation',
                'description': 'Event request for Youth Education Foundation',
                'record_number': 'ER-2024-016',
                'client_name': 'Youth Education Foundation',
                'event_type': 'Exhibition',
                'expected_number': 350,
                'expected_budget': 55000.00,
                'from_date': now.date() - timedelta(days=15),
                'to_date': now.date() - timedelta(days=13),
                'has_decorations': True,
                'has_meals': True,
                'has_parties': False,
                'has_drinks': False,
                'has_filming': True,
                'created_by': cs_user,
                'status': 'closed',
                'created_at': now - timedelta(days=75),
                'updated_at': now - timedelta(days=10),
                'scs_handler': scs_user,
                'scs_comment': 'Youth educational event. Community service opportunity. Positive PR value.',
                'scs_handled_at': now - timedelta(days=74),
                'fm_handler': fm_user,
                'fm_feedback': 'Non-profit pricing applied. Budget covers costs with minimal margin. Approved for community relations.',
                'fm_handled_at': now - timedelta(days=73),
                'admin_handler': admin_user,
                'admin_decision': 'APPROVED. CSR initiative. Good for company image. Support local education.',
                'admin_handled_at': now - timedelta(days=72),
                'description_of_decorations': 'Science-themed decorations. Student project display booths. Awards stage setup.',
                'description_of_meals': 'Lunch for participants and judges. Kid-friendly menu. Snack stations. Dietary accommodations.',
                'description_of_music': 'Background music in common areas. PA system for announcements and awards ceremony.',
                'description_of_poster': 'Fair schedule boards. Category markers. Directional signs. Sponsor acknowledgment.',
                'description_of_filming': 'Event documentation. Award ceremony recording. Promotional footage for next year.',
                'other_needs': 'Display tables for 80 projects. Judging coordination. Award trophies. Registration desk. Parent waiting area. First aid.',
            },
        ]

        created_count = 0
        for event_data in event_requests_data:
            record_number = event_data['record_number']
            
            # 检查是否已存在
            if EventRequest.objects.filter(record_number=record_number).exists():
                self.stdout.write(
                    self.style.WARNING(f'事件请求 {record_number} 已存在，跳过')
                )
                continue
            
            # 创建事件请求
            EventRequest.objects.create(**event_data)
            
            created_count += 1
            self.stdout.write(
                self.style.SUCCESS(f'✓ 成功创建事件请求: {record_number} - {event_data["title"]} ({event_data["status"]})')
            )
        
        self.stdout.write(
            self.style.SUCCESS(f'\n总计创建 {created_count} 条事件请求')
        )