# Generated by Django 5.2.7 on 2025-10-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to SCS'), ('scs_reviewed', 'SCS Reviewed'), ('fm_reviewed', 'FM Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('scs_comment', models.TextField(blank=True)),
                ('scs_handled_at', models.DateTimeField(blank=True, null=True)),
                ('fm_feedback', models.TextField(blank=True)),
                ('fm_handled_at', models.DateTimeField(blank=True, null=True)),
                ('admin_decision', models.TextField(blank=True)),
                ('admin_handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
