# Generated by Django 5.2.7 on 2025-10-27 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='admin_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_event_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_event_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='current_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_event_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='fm_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_event_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='scs_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scs_event_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
