# Generated by Django 5.2.7 on 2025-10-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='description_of_decorations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='description_of_drinks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='description_of_filming',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='description_of_meals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='description_of_music',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='description_of_poster',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='event_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='expected_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='expected_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='from_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='has_decorations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='has_drinks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='has_filming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='has_meals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='has_parties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='other_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='record_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='to_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted to SCS'), ('scs_reviewed', 'SCS Reviewed'), ('fm_reviewed', 'FM Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
