# Generated by Django 5.2.7 on 2025-10-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent_to_employee', 'Sent to Employee'), ('plan_submitted', 'Plan Submitted'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('employee_plan', models.TextField(blank=True, help_text='员工填写的工作计划')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, help_text='预估预算', max_digits=10, null=True)),
                ('employee_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
