# Generated by Django 5.2.7 on 2025-10-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='申请的预算金额', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted to FM'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('fm_decision', models.TextField(blank=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='批准的预算金额', max_digits=10, null=True)),
                ('fm_handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
