# Generated by Django 5.2.7 on 2025-10-29 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_approvals', '0002_initial'),
        ('event_requests', '0003_eventrequest_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetapproval',
            name='approved_amount',
        ),
        migrations.RemoveField(
            model_name='budgetapproval',
            name='fm_handled_at',
        ),
        migrations.RemoveField(
            model_name='budgetapproval',
            name='related_task',
        ),
        migrations.AddField(
            model_name='budgetapproval',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_approvals', to='event_requests.eventrequest'),
        ),
        migrations.AlterField(
            model_name='budgetapproval',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted to FM'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
